version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for database data

volumes:
  postgres_data:
